# Generated by Django 3.0.6 on 2020-05-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='defult'),
            preserve_default=False,
        ),
    ]
