# Generated by Django 3.0.6 on 2020-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_author_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='req_time',
            field=models.CharField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
